#!/usr/bin/env bash
#
# Install Home Brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install bundler so we can use the Brewfile
brew tab Homebrew/brewdler

mkdir -p "$(brew --prefix)/etc"
brew brewdle

echo 'address=/.dev/127.0.0.1' > "$(brew --prefix)/etc"/dnsmasq.conf
sudo cp -v $(brew --prefix dnsmasq)/homebrew.mxcl.dnsmasq.plist /Library/LaunchDaemons

# Remove outdated versions from the cellar
brew cleanup
